#!/usr/bin/env node
/**
 * Static build for GitHub Pages.
 *
 * Route handlers that accept POST can't be exported, so the API directory is
 * moved aside for the duration of the build and always restored. The client
 * already uses the in-browser assistant and the email relay in this mode.
 *
 *   NEXT_PUBLIC_BASE_PATH=/portfolio NEXT_PUBLIC_SITE_URL=https://user.github.io/portfolio \
 *     node scripts/build-static.mjs
 */
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const apiDir = "src/app/api";
const parkedDir = ".static-build-api";

if (existsSync(parkedDir)) {
  console.error(`${parkedDir} exists — a previous static build was interrupted. Move it back to ${apiDir} first.`);
  process.exit(1);
}

// Route types generated by `next dev` still reference the API routes.
rmSync(".next/dev/types", { recursive: true, force: true });

const hadApi = existsSync(apiDir);
if (hadApi) renameSync(apiDir, parkedDir);

/**
 * Generated icons and social images are exported without a file extension
 * (e.g. out/opengraph-image), which static hosts serve as octet-stream, and
 * icon links miss the base path. Give them .png names and fix references.
 */
function fixMetadataImages(dir) {
  const basePath = (process.env.NEXT_PUBLIC_BASE_PATH ?? "").replace(/\/+$/, "");
  const images = ["icon", "apple-icon", "opengraph-image", "twitter-image"];
  const walk = (d) =>
    readdirSync(d).flatMap((name) => {
      const path = join(d, name);
      return statSync(path).isDirectory() ? walk(path) : [path];
    });
  const files = walk(dir);
  for (const file of files) {
    const name = file.split("/").pop();
    if (images.includes(name)) copyFileSync(file, `${file}.png`);
  }
  const iconRef = new RegExp(`(["'(])(?:${basePath})?/(apple-icon|icon)\\?[0-9a-f]+`, "g");
  const socialRef = /\/(opengraph-image|twitter-image)\?[0-9a-f]+/g;
  for (const file of files.filter((f) => /\.(html|txt|webmanifest)$/.test(f))) {
    const source = readFileSync(file, "utf8");
    const fixed = source
      .replace(iconRef, `$1${basePath}/$2.png`)
      .replace(socialRef, "/$1.png");
    if (fixed !== source) writeFileSync(file, fixed);
  }
}

let status = 1;
try {
  const result = spawnSync("npx", ["next", "build"], {
    stdio: "inherit",
    env: { ...process.env, NEXT_PUBLIC_STATIC_EXPORT: "true" },
  });
  status = result.status ?? 1;
  if (status === 0) {
    // Serve the _next/ directory as-is on GitHub Pages.
    writeFileSync("out/.nojekyll", "");
    fixMetadataImages("out");
  }
} finally {
  if (hadApi) renameSync(parkedDir, apiDir);
}
process.exit(status);
